name: englabor_app
description: App Flutter EngLabor
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  connectivity_plus: ^4.0.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  mask_text_input_formatter: ^2.9.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
